version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: my_database
    ports:
      - "5433:5432"

  app:
    build: .
    command: /bin/bash
    volumes:
      - .:/usr/src/app
    ports:
      - "3011:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/my_database
